// All the coffees the roulette can pick from, plus local shops.
// Colors are tuned to the neutral / coffee palette (cream, tan, taupe, charcoal).

export const COFFEES = [
  {
    name: "Espresso",
    emoji: "☕",
    color: "#3d2817",
    description: "Pure, concentrated, no nonsense.",
    recipe: [
      "Grind 18g of dark-roast beans fine, like table salt.",
      "Tamp evenly into the portafilter with ~30 lbs of pressure.",
      "Pull a 25–30 second shot — aim for ~36g out.",
      "Serve in a warmed demitasse. Drink while the crema is alive.",
    ],
  },
  {
    name: "Americano",
    emoji: "🖤",
    color: "#4a3525",
    description: "Espresso loosened with hot water. Long and contemplative.",
    recipe: [
      "Pull a double shot of espresso (~36g).",
      "Heat 6 oz of water to roughly 200°F.",
      "Pour the hot water into the cup first, then add the espresso on top to preserve crema.",
      "Stir once. Sip.",
    ],
  },
  {
    name: "Cappuccino",
    emoji: "🫧",
    color: "#8b6f4e",
    description: "One-third espresso, one-third milk, one-third foam.",
    recipe: [
      "Pull a double shot of espresso into a 6 oz cup.",
      "Steam 4 oz of whole milk to 140°F with dense microfoam.",
      "Pour the milk in a slow, centered stream — let foam mound on top.",
      "Dust with cocoa powder if you're feeling festive.",
    ],
  },
  {
    name: "Latte",
    emoji: "🥛",
    color: "#b8967a",
    description: "Espresso swimming in silky steamed milk.",
    recipe: [
      "Pull a double shot of espresso into a 12 oz cup.",
      "Steam 10 oz of milk to 150°F with a thin layer of microfoam.",
      "Pour the milk from a height, then drop low to draw latte art.",
      "Try a rosetta — wiggle, then pull through.",
    ],
  },
  {
    name: "Flat White",
    emoji: "⚪",
    color: "#a08469",
    description: "Australian classic. Stronger ratio, velvety microfoam.",
    recipe: [
      "Pull a ristretto double shot (~30g out, intense and sweet).",
      "Steam 5 oz of whole milk to 140°F — silky microfoam.",
      "Pour smoothly to integrate, leaving a thin 5mm foam cap.",
      "Serve in a 6 oz ceramic cup.",
    ],
  },
  {
    name: "Mocha",
    emoji: "🍫",
    color: "#5a3a25",
    description: "Espresso, chocolate, milk. The pastry of drinks.",
    recipe: [
      "Add 2 tbsp of chocolate syrup or melted ganache to the cup.",
      "Pull a double shot of espresso onto the chocolate and stir.",
      "Steam 8 oz of milk and pour over.",
      "Top with whipped cream and a shaving of dark chocolate.",
    ],
  },
  {
    name: "Macchiato",
    emoji: "🎯",
    color: "#6b4a30",
    description: "Espresso 'marked' with a dollop of foam.",
    recipe: [
      "Pull a double shot of espresso into a small cup.",
      "Steam a small amount of milk into thick foam.",
      "Spoon (don't pour) a dollop of foam onto the espresso.",
      "Drink immediately.",
    ],
  },
  {
    name: "Cortado",
    emoji: "🥃",
    color: "#8a6646",
    description: "Equal parts espresso and warm milk. Balanced.",
    recipe: [
      "Pull a double shot of espresso into a 4 oz glass.",
      "Steam 2 oz of milk to 130°F — minimal foam, just warmed.",
      "Pour the milk slowly to mix evenly with the espresso.",
      "Drink in three or four sips.",
    ],
  },
  {
    name: "Cold Brew",
    emoji: "🧊",
    color: "#2d1a0c",
    description: "Slow-steeped, smooth, low-acid.",
    recipe: [
      "Coarsely grind 1 cup of beans (like sea salt).",
      "Combine with 4 cups of cold filtered water in a jar.",
      "Steep in the fridge for 12–18 hours.",
      "Strain through a paper filter. Serve over ice, dilute to taste.",
    ],
  },
  {
    name: "Iced Latte",
    emoji: "🧋",
    color: "#c9a987",
    description: "Espresso, cold milk, ice. Infinitely repeatable.",
    recipe: [
      "Pull a double shot of espresso into a 16 oz glass.",
      "Fill the glass with ice cubes.",
      "Top with 10 oz of cold whole milk.",
      "Stir well — espresso wants to settle at the bottom.",
    ],
  },
  {
    name: "Affogato",
    emoji: "🍨",
    color: "#4d3320",
    description: "Vanilla gelato 'drowned' in hot espresso.",
    recipe: [
      "Scoop a generous ball of vanilla gelato into a chilled cup.",
      "Pull a hot double shot of espresso.",
      "Pour the espresso directly over the gelato.",
      "Eat with a small spoon, fast, before it melts.",
    ],
  },
  {
    name: "Pour Over",
    emoji: "🌊",
    color: "#6e4a30",
    description: "A meditative, clean cup.",
    recipe: [
      "Grind 22g of beans to medium-coarse (like kosher salt).",
      "Rinse a paper filter with hot water, discard the water.",
      "Bloom with 50g of 200°F water for 30 seconds.",
      "Pour in slow concentric circles to 360g total. Drawdown ~3:30.",
    ],
  },
  {
    name: "Chai Latte",
    emoji: "🍵",
    color: "#b3814b",
    description: "Spiced black tea with steamed milk. Cozy in a cup.",
    recipe: [
      "Brew a concentrate: 2 black tea bags + cardamom, cinnamon, ginger, cloves in 4 oz water.",
      "Simmer 5 minutes, then strain.",
      "Add honey to taste while warm.",
      "Top with 6 oz of steamed milk and a dust of cinnamon.",
    ],
  },
  {
    name: "Dirty Chai",
    emoji: "🌶️",
    color: "#8e5a30",
    description: "Chai latte with a shot of espresso.",
    recipe: [
      "Make a chai latte (or use a quality chai concentrate).",
      "Pull a single shot of espresso.",
      "Pour the espresso into the bottom of the cup first.",
      "Add the chai and steamed milk over top.",
    ],
  },
  {
    name: "Vienna Coffee",
    emoji: "🎼",
    color: "#4a2e1a",
    description: "Strong black coffee crowned with whipped cream.",
    recipe: [
      "Brew 8 oz of strong drip or French press coffee.",
      "Whip heavy cream to soft peaks (do not sweeten the coffee).",
      "Float a generous spoonful of whipped cream on the surface.",
      "Sip through the cream — don't stir.",
    ],
  },
  {
    name: "Turkish Coffee",
    emoji: "🫖",
    color: "#2a160a",
    description: "Unfiltered, fine-ground, simmered in a cezve.",
    recipe: [
      "Grind beans to a powder, finer than espresso.",
      "Combine 1 heaping tsp coffee + 1 tsp sugar + 3 oz cold water in a cezve.",
      "Heat slowly until foam rises — pull off heat before it boils.",
      "Pour foam first into the cup, then the rest. Let grounds settle.",
    ],
  },
];

export const SHOPS = [
  {
    name: "Beagle's Bakery & Espresso",
    address: "4896 MT-200, Thompson Falls",
    rating: 4.9,
    phone: "(406) 827-2579",
    hours: "Mon–Tue 6:30–3, Closed Wed, Thu–Sun 6:30–3",
    note: "Cozy Montana-style spot with breakfast burritos and dogs welcome.",
  },
  {
    name: "Scotchman's Coffee",
    address: "925 W Main St, Thompson Falls",
    rating: 4.6,
    phone: "(406) 258-8064",
    hours: "Weekdays 7–4, Weekends 8–3",
    note: "Locally roasted beans, seasonal flavors, kids corner.",
  },
  {
    name: "Cheri's Espresso",
    address: "Thompson Falls",
    rating: 4.8,
    phone: "(406) 827-5282",
    hours: "Tue–Fri 7:30–3, Sat 9–1",
    note: "Drive-thru. Famous for spiced chai lattes and fair prices.",
  },
  {
    name: "Royal Buzz Coffee",
    address: "1222 Maiden Ln, Thompson Falls",
    rating: 5.0,
    phone: "(406) 802-2001",
    hours: "Daily 7–2",
    note: "Second location of a local favorite — frappes get rave reviews.",
  },
  {
    name: "Bearfoot Bakery & Espresso",
    address: "925 W Main St, Thompson Falls",
    rating: 3.0,
    phone: "(406) 847-1024",
    hours: "Daily 6:30–7",
    note: "Donuts, espresso, long hours.",
  },
  {
    name: "Ace's Coffee",
    address: "178 MT-200, Plains",
    rating: 4.9,
    phone: null,
    hours: "Mon–Fri 6:30–4, Sat 7–2",
    note: "Best iced americano in Plains, per the regulars.",
  },
  {
    name: "Uncommon Grounds Espresso",
    address: "12 MT-28 N, Plains",
    rating: 4.7,
    phone: "(406) 529-9255",
    hours: "Daily 6:30–4:30",
    note: "Drive-thru hut. Open every day, including Sundays.",
  },
];
